workflows:
  default-workflow:
    name: Default Workflow
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter pub get
      - flutter build apk --release --no-tree-shake-icons
    artifacts:
      - build/**/outputs/**/*.apk