workflows:
  default-workflow:
    name: Default Workflow
    environment:
      flutter: stable
      xcode: latest
      vars:
        GRADLE_OPTS: "-Xmx6g -Xms2g"
    scripts:
      - echo "org.gradle.jvmargs=-Xmx6g -Xms2g" >> android/gradle.properties
      - flutter clean
      - flutter pub get
      - flutter build appbundle --release --no-tree-shake-icons
    artifacts:
      - build/**/outputs/**/*.aab